### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by yatskovanatoly** [sukalov/mktour#10]
# TODO:
**tournament dashboard**:
  - [x] games tab with no interactivity for viewers @yatskovanatoly
  - [x] setGameResult with no long-press. simple click @yatskovanatoly
  - [x] #12
  - [x] remove 'generate new round' button for non-admins
  - [x] remove player stats when games regenerated
  - [x] setGameResult only when tournament is started
  - [x] 'start tournament' button sets tournament status in db and sends separate ws-message
  - [x] tournament END. buttons and appearance of a closed tournament
  - [x] delete tournament button (with single checkbox confirmation)
  - [x] ws-messages
    - [x] for new-round
    - [x] for game-result
    - [x] HANDLERS for new-round
    - [x] HANDLERS for game-result
    - [x] throw ws-client to round one if tournament reset
    - [x] set game result handler. add setQueryData
    - [x] set tournament status (start tournament, reset tournament) handlers. add setQueryData
  - [x] add checker for 'zero games with no result'. generate next round when present
  - [x] **FIX** server check of user status on set tournament status 
  - [x] **FIX!!!!** server check of user status on ALLL ACTIONS with tournament dashboard. checking user id is not enough, must check the status somehow (in some not too expensive way)
    - [x] FIX sometimes roundRobinGenerator crashes with error 'blackEntity undefined'
    - [x] try moving round generation to client [with props `(PlayerModel[], GameModel[], roundNumber)`]
    - [x] delete tournament

**other:**
  - [x] rename column 'exited' to 'out' in players_to_tournaments table
  - [x] add a check for joining a lichess team club. if a club already exists on the platform associated with that team, do not allow the creation of a new one.
  - [x] provide a link to the existing team.
  - [x] do not allow the creation of a new club if the user has a club without any completed tournaments. instead, suggest renaming the existing club and redirect them to its dashboard.
  - [x] add the option to delete a club.
  - [x] deletion and editing of players in a club.
  - [x] all clubs page: `clubs/all`
  - [x] club page: `club/[id]` @yatskovanatoly 
  - [x] delete user
  - [x] FIX add-player fab ~propagation on open drawer~ fast clicking bug @yatskovanatoly
